### ISSUE TITLE
`See the eslint-plugin-example example for examples of more real world fixes.`

### ISSUE THREAD

**Issue by 12finger** [DarkPurple141/eslint-codemod-utils#51]
in the readme you link to examples. but the link is broken.
 would love to see those!

**Comment by DarkPurple141** [comment]
Hey mate sorry just seeing this!

You can find the examples here: https://github.com/DarkPurple141/eslint-codemod-utils/tree/master/packages/eslint-plugin-codemod - looks like a typo in the link

**Comment by DarkPurple141** [comment]
Lodged a fix in #52
